#!/usr/bin/env bash
# Refresh the vendored framework docs in docs/vendor/ at pinned refs.
# Usage: scripts/update-vendor-docs.sh
# Bump a ref below when composer.lock moves to a new major version.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/docs/vendor"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# name | repository | ref | path inside the repository ("." for the root)
SOURCES=(
  "laravel|https://github.com/laravel/docs.git|12.x|."
  "livewire|https://github.com/livewire/livewire.git|3.x|docs"
  "volt|https://github.com/livewire/volt.git|main|README.md"
  "pest|https://github.com/pestphp/docs.git|3.x|."
)

rm -rf "$DEST"
mkdir -p "$DEST"
{
  echo "# Vendored documentation sources"
  echo
  echo "Generated by \`scripts/update-vendor-docs.sh\`. Do not edit files under"
  echo "\`docs/vendor/\` by hand; rerun the script instead."
  echo
  echo "| Docs | Repository | Ref | Commit |"
  echo "|---|---|---|---|"
} > "$DEST/SOURCES.md"

for entry in "${SOURCES[@]}"; do
  IFS='|' read -r name repo ref path <<< "$entry"
  git clone --quiet --depth 1 --branch "$ref" "$repo" "$TMP/$name"
  sha="$(git -C "$TMP/$name" rev-parse HEAD)"
  mkdir -p "$DEST/$name"
  if [ "$path" = "." ]; then
    find "$TMP/$name" -maxdepth 1 -name '*.md' -exec cp {} "$DEST/$name/" \;
  elif [ -d "$TMP/$name/$path" ]; then
    cp -R "$TMP/$name/$path/." "$DEST/$name/"
  else
    cp "$TMP/$name/$path" "$DEST/$name/"
  fi
  for license in LICENSE LICENSE.md LICENSE.txt; do
    [ -f "$TMP/$name/$license" ] && cp "$TMP/$name/$license" "$DEST/$name/LICENSE.md" && break
  done
  echo "| $name | ${repo%.git} | \`$ref\` | \`$sha\` |" >> "$DEST/SOURCES.md"
done

echo "Vendored docs written to $DEST"
